name: Run pre-merge tests

on:
  pull_request:
    branches: [ main ]
  
jobs:
                 
  maven-deploy:
    # build with maven to make sure things compile correctly
      
    name: Try to compile with maven
    runs-on: ubuntu-latest 

    steps:
    
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'zulu'

          
      - name: Publish to Apache Maven Central
        run: mvn package
